# Generated by Django 4.2.18 on 2025-09-28 06:07

# Standard Python Libraries
import uuid

# Third-Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashPromoModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("product_id", models.UUIDField()),
                ("store_id", models.UUIDField()),
                (
                    "promo_price_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("promo_price_currency", models.CharField(default="USD", max_length=3)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("user_segments", models.JSONField(default=list)),
                ("max_radius_km", models.FloatField(default=2.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flash Promo",
                "verbose_name_plural": "Flash Promos",
                "db_table": "flash_promos",
            },
        ),
        migrations.CreateModel(
            name="ReservationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("product_id", models.UUIDField()),
                ("store_id", models.UUIDField()),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "db_table": "reservations",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                ("user_segment", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
