# Generated by Django 4.2.18 on 2025-09-28 19:11

# Third-Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="user_segment",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="user_segments",
            field=models.JSONField(default=list),
        ),
    ]
