# Generated by Django 4.2.18 on 2025-09-29 05:12

# Third-Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_remove_usermodel_user_segment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationmodel",
            name="flash_promo_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
